### ISSUE TITLE
Any tips on saving the data collections?

### ISSUE THREAD

**Issue by gam-ragnar** [pmwisdom/mirrorcell-geolocation-plus#2]
I am trying to save the last coordinates into collection using collection2 autoValue https://github.com/aldeed/meteor-collection2. Sadly it requires the object to be available in server side so no luck there. Essentially I want to save this on the background without exposing any UI field to the user. Any advice on best way to achieve this.

**Comment by pmwisdom** [comment]
Hey @timfam, I'm not 100% what your trying to do. If you gave me some sample code I might be able to help you better. Apologies, I've never used autoValue before.

Any reason your not just calling a meteor method that inserts / updates the coordinates in a collection?

**Comment by gam-ragnar** [comment]
I am using it with Orion/Autoform and the user needs to enter some info and geolocation gets saved along with the form data. Autoform uses simpleSchema and I need the validation that comes with it.
I will try another approach if that don't work then I may result to Meteor.methods. Thanks for your response

**Comment by pmwisdom** [comment]
No problem. Good luck with the solution.
