### ISSUE TITLE
Install as local package not working

### ISSUE THREAD

**Issue by kjetilge** [pmwisdom/mirrorcell-geolocation-plus#4]
When trying to install as local package I get:
`Could not satisfy all the specified constraints:
Error: conflict: constraint session@1.0.5 is not satisfied by 1.0.4.
Constraints on session come from:
  <top level>
  meteor-platform@1.2.0
  mirrorcell:geolocation-plus@1.1.7`

**Comment by pmwisdom** [comment]
Is that the devel meteor branch your running? 

Since your running it as a local package, you could force the session version to 1.0.5 for now.

Replace this line in package.js

``` javascript

api.use(['session', 'reactive-var']);

```

With 

``` javascript

api.use(['session@1.0.5', 'reactive-var']);

```

Hope that works.

**Comment by kjetilge** [comment]
Thanks, it worked.
