### ISSUE TITLE
Mobile Background

### ISSUE THREAD

**Issue by ghost** [pmwisdom/mirrorcell-geolocation-plus#5]
Hi! Does this plugin work in background on mobile devices?

**Comment by pmwisdom** [comment]
Hi @irisbanciu, this is currently not a viable solution for mobile devices in the background. The biggest reason being, when your app gets killed (and it will at some point on android), the foreground tracker here will also be killed. I am currently working on a background location service for this plugin. iOS is done, Android is on its way. So look forward to that in the near future.
