### ISSUE TITLE
Support for newer version of cordova

### ISSUE THREAD

**Issue by agoudsmit** [pmwisdom/mirrorcell-geolocation-plus#6]
We tried to use this package with Meteor 1.3 (which has cordova v. 6) and we keep getting compile errors. Will you be adding support for Meteor 1.3?

**Comment by pmwisdom** [comment]
Cordova 6 and Meteor 1.3 are both fully supported. You probably need to install the android pre-requisites.

**Comment by pmwisdom** [comment]
@agoudsmit I haven't had any problem with Meteor 1.3 and this plugin. Can you please submit logs of the compiler errors?

**Comment by agoudsmit** [comment]
Hi Paul,

Thanks for the quick reply. I’ll get back to you with that info.

best regards,

arnaud

**Comment by agoudsmit** [comment]
We have tested it properly and its a cordova issue. Thanks for the quick response either way.
